apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  namespace: josh-apps
spec:
  ports:
    - targetPort: ${PORT}
      port: 8443
      name: http
    - targetPort: ${WEBHOOK_PORT}
      port: 30001
      name: webhook
  selector:
    app: ${SERVICE_NAME}
